alias cat='bat --theme=OneHalfDark'
alias ls='exa'
alias dockaudio='$dotfiles_root/bin/set-xps-dock-audio.sh'
alias nsh='nix-shell --command fish'
alias fuu='killall -9 rider'
alias fd='fdfind'
alias fcd='cd (fd -t d | fzf)'
alias top='procs --watch --sortd cpu'
alias y='maybe-yarn'